import { dateOfBirthFromApproximateAge } from "@/domain/display/compute-age-from-date-of-birth";
import type { SeedMember } from "@/db/seed/seed-member-shape";

export const chinaSeedProfiles: SeedMember[] = [
  {
    userId: "seed-wei-lin",
    displayName: "Wei Lin",
    emailLocalPart: "wei.lin",
    country: "CN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(30),
    heightCm: 176,
    city: "Beijing",
    region: "Beijing",
    religion: "None",
    education: "Master's in Computer Science",
    educationBand: "masters",
    profession: "Software Engineer",
    annualIncomeAmount: 380_000,
    incomeCurrency: "CNY",
    maritalStatus: "never_married",
    diet: "no_preference",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "I work on maps software in Beijing and take the night train home to Tianjin for holidays. I cook simple noodles and want a partner who is independent and close to her parents.",
    isOnlyChild: true,
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Mandarin", "English"],
    photoPath: "/profile_male_10.avif",
    medicalStatus: "clear",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 25,
      maxAge: 33,
      minHeightCm: 158,
      maxHeightCm: 172,
      countries: ["CN"],
      religions: [],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-yuna-chen",
    displayName: "Yuna Chen",
    emailLocalPart: "yuna.chen",
    country: "CN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(27),
    heightCm: 163,
    city: "Shanghai",
    region: "Shanghai",
    religion: "Buddhist",
    education: "MBA",
    educationBand: "masters",
    profession: "Product Manager",
    annualIncomeAmount: 320_000,
    incomeCurrency: "CNY",
    maritalStatus: "never_married",
    diet: "no_preference",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "Product manager who still visits temples with my grandmother. I like weekend museums and quiet dinners in the former French Concession. Looking for someone steady, not flashy.",
    isOnlyChild: true,
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Mandarin", "Shanghainese", "English"],
    photoPath: "/profile_female_10.avif",
    medicalStatus: "has_notes",
    medicalNotes: "Hypothyroidism, stable on a low daily dose. Labs are checked twice a year.",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 28,
      maxAge: 36,
      minHeightCm: 172,
      maxHeightCm: 188,
      countries: ["CN"],
      religions: [],
      educationBands: ["bachelors", "masters", "doctorate"],
    },
  },
  {
    userId: "seed-hao-zhang",
    displayName: "Hao Zhang",
    emailLocalPart: "hao.zhang",
    country: "CN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(32),
    heightCm: 180,
    city: "Shenzhen",
    region: "Guangdong",
    religion: "prefer_not_to_say",
    education: "Bachelor's in Engineering",
    educationBand: "bachelors",
    profession: "Hardware Engineer",
    annualIncomeAmount: 450_000,
    incomeCurrency: "CNY",
    maritalStatus: "never_married",
    diet: "non_vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "I build phones by day and hike Wutong Mountain on Saturdays. Open to relocating within China. I want a partner who likes cities but still goes home for Spring Festival.",
    isOnlyChild: false,
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Mandarin", "Cantonese", "English"],
    photoPath: "/profile_male_11.avif",
    medicalStatus: "clear",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 26,
      maxAge: 34,
      minHeightCm: 155,
      maxHeightCm: 170,
      countries: ["CN"],
      religions: [],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-mei-wang",
    displayName: "Mei Wang",
    emailLocalPart: "mei.wang",
    country: "CN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(29),
    heightCm: 158,
    city: "Chengdu",
    region: "Sichuan",
    religion: "None",
    education: "Master's in Education",
    educationBand: "masters",
    profession: "Primary School Teacher",
    annualIncomeAmount: 180_000,
    incomeCurrency: "CNY",
    maritalStatus: "never_married",
    diet: "no_preference",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "Primary school teacher in Chengdu. I love spicy food, pandas, and staying near my parents. Looking for a kind partner who wants children and a slower city life.",
    isOnlyChild: true,
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Mandarin", "Sichuanese"],
    photoPath: "/profile_female_11.avif",
    hideIncome: true,
    medicalStatus: "clear",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 28,
      maxAge: 36,
      minHeightCm: 170,
      maxHeightCm: 185,
      countries: ["CN"],
      religions: [],
      educationBands: ["bachelors", "masters"],
    },
  },
];
