import { dateOfBirthFromApproximateAge } from "@/domain/display/compute-age-from-date-of-birth";
import type { SeedMember } from "@/db/seed/seed-member-shape";

/** Four Germany members. Photos reuse the existing public/profile*.avif set. */
export const germanySeedProfiles: SeedMember[] = [
  {
    userId: "seed-lukas-weber",
    displayName: "Lukas Weber",
    emailLocalPart: "lukas.weber",
    country: "DE",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(33),
    heightCm: 184,
    city: "Berlin",
    region: "Berlin",
    religion: "None",
    education: "Diplom-Ingenieur",
    educationBand: "masters",
    profession: "Mechanical engineer",
    annualIncomeAmount: 72_000,
    incomeCurrency: "EUR",
    maritalStatus: "never_married",
    diet: "no_preference",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "Engineer who bikes to work and bakes on Sundays. I want a long-term partnership, maybe children, and someone who likes both museums and forests.",
    hasChildren: "none",
    wantsChildren: "open",
    languagesSpoken: ["German", "English"],
    photoPath: "/profile4.avif",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 27,
      maxAge: 37,
      minHeightCm: 158,
      maxHeightCm: 175,
      countries: ["DE"],
      religions: [],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-anna-keller",
    displayName: "Anna Keller",
    emailLocalPart: "anna.keller",
    country: "DE",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(30),
    heightCm: 168,
    city: "Munich",
    region: "Bavaria",
    religion: "Christian",
    education: "Staatsexamen Medicine",
    educationBand: "doctorate",
    profession: "Physician",
    annualIncomeAmount: 85_000,
    incomeCurrency: "EUR",
    maritalStatus: "never_married",
    diet: "no_preference",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "Hospital doctor in Munich. I hike in the Alps when shifts allow. Looking for a partner who respects my work and wants a family in the next few years.",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["German", "English"],
    photoPath: "/profile9.avif",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 30,
      maxAge: 40,
      minHeightCm: 175,
      maxHeightCm: 195,
      countries: ["DE"],
      religions: ["Christian", "None", "prefer_not_to_say"],
      educationBands: ["bachelors", "masters", "doctorate"],
    },
  },
  {
    userId: "seed-jonas-berg",
    displayName: "Jonas Berg",
    emailLocalPart: "jonas.berg",
    country: "DE",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(36),
    heightCm: 176,
    city: "Hamburg",
    region: "Hamburg",
    religion: "prefer_not_to_say",
    education: "Master's in History",
    educationBand: "masters",
    profession: "Journalist",
    annualIncomeAmount: 54_000,
    incomeCurrency: "EUR",
    maritalStatus: "divorced",
    diet: "vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "Journalist, divorced, one child who stays with me every other week. I want a partner who is comfortable with that and likes rainy walks by the Elbe.",
    hasChildren: "has_children",
    wantsChildren: "open",
    languagesSpoken: ["German", "English"],
    photoPath: "/profile10.avif",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 28,
      maxAge: 42,
      minHeightCm: 155,
      maxHeightCm: 175,
      countries: ["DE"],
      religions: [],
      educationBands: [],
    },
  },
  {
    userId: "seed-leila-hassan",
    displayName: "Leila Hassan",
    emailLocalPart: "leila.hassan",
    country: "DE",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(28),
    heightCm: 166,
    city: "Cologne",
    region: "North Rhine-Westphalia",
    religion: "Muslim",
    education: "Bachelor's in Law",
    educationBand: "bachelors",
    profession: "Legal counsel",
    annualIncomeAmount: 61_000,
    incomeCurrency: "EUR",
    maritalStatus: "never_married",
    diet: "no_preference",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "In-house counsel, born in Cologne, family from Lebanon. I want a marriage with someone who takes faith seriously without being rigid, and who likes carnival more than they admit.",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["German", "Arabic", "English"],
    photoPath: "/profile11.avif",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 28,
      maxAge: 36,
      minHeightCm: 172,
      maxHeightCm: 190,
      countries: ["DE"],
      religions: ["Muslim"],
      educationBands: ["bachelors", "masters"],
    },
  },
];
