import { dateOfBirthFromApproximateAge } from "@/domain/display/compute-age-from-date-of-birth";
import type { SeedMember } from "@/db/seed/seed-member-shape";

/**
 * The original 18 hardcoded cards from the browse page, now with bios and India-specific fields.
 * Photos stay mapped 1:1 to /profile1.avif … /profile18.avif.
 */
export const indiaSeedProfiles: SeedMember[] = [
  {
    userId: "seed-karan-kapoor",
    displayName: "Karan Kapoor",
    emailLocalPart: "karan.kapoor",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(29),
    heightCm: 185,
    city: "Dehradun",
    region: "Uttarakhand",
    religion: "Hindu",
    education: "Diploma",
    educationBand: "diploma",
    profession: "Software Engineer",
    annualIncomeAmount: 680_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "I grew up in the hills and still hike every weekend. I write software for a living and cook a proper Sunday dal. Looking for someone kind who wants a calm home and the occasional mountain trip.",
    motherTongue: "Hindi",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Hindi", "English"],
    photoPath: "/profile1.avif",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 24,
      maxAge: 32,
      minHeightCm: 152,
      maxHeightCm: 175,
      countries: ["IN"],
      religions: ["Hindu"],
      educationBands: ["diploma", "bachelors", "masters"],
    },
  },
  {
    userId: "seed-rahul-verma",
    displayName: "Rahul Verma",
    emailLocalPart: "rahul.verma",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(28),
    heightCm: 173,
    city: "Delhi",
    region: "Delhi",
    religion: "Hindu",
    education: "B.Tech",
    educationBand: "bachelors",
    profession: "Accountant",
    annualIncomeAmount: 550_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "Numbers by day, cricket in the park on Sundays. Close to my parents in Delhi and hoping to stay in the city. I want a partner who values family dinners and honest conversations.",
    motherTongue: "Hindi",
    familyType: "joint",
    isManglik: "unknown",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Hindi", "English"],
    photoPath: "/profile2.avif",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 23,
      maxAge: 30,
      minHeightCm: 150,
      maxHeightCm: 170,
      countries: ["IN"],
      religions: ["Hindu", "Jain"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-ananya-singh",
    displayName: "Ananya Singh",
    emailLocalPart: "ananya.singh",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(25),
    heightCm: 165,
    city: "Bangalore",
    region: "Karnataka",
    religion: "Muslim",
    education: "MCA",
    educationBand: "masters",
    profession: "Data Analyst",
    annualIncomeAmount: 450_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "non_vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "I moved to Bangalore for work and stayed for the weather and the food. I like long walks, Urdu poetry, and weekend calls with my sister. Looking for someone thoughtful and ambitious.",
    motherTongue: "Hindi",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "open",
    languagesSpoken: ["Hindi", "English", "Urdu"],
    photoPath: "/profile3.avif",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 26,
      maxAge: 34,
      minHeightCm: 170,
      maxHeightCm: 190,
      countries: ["IN"],
      religions: ["Muslim"],
      educationBands: ["bachelors", "masters", "doctorate"],
    },
  },
  {
    userId: "seed-vikram-patel",
    displayName: "Vikram Patel",
    emailLocalPart: "vikram.patel",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(30),
    heightCm: 183,
    city: "Chennai",
    region: "Tamil Nadu",
    religion: "Sikh",
    education: "B.Com",
    educationBand: "bachelors",
    profession: "Sales Manager",
    annualIncomeAmount: 650_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "non_vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "I travel a lot for work and still make it home for gurdwara on Sundays. I want a partner who is independent, laughs easily, and does not mind relocating someday.",
    motherTongue: "Punjabi",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Punjabi", "English", "Hindi", "Tamil"],
    photoPath: "/profile4.avif",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 24,
      maxAge: 32,
      minHeightCm: 155,
      maxHeightCm: 175,
      countries: ["IN"],
      religions: ["Sikh", "Hindu"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-neha-gupta",
    displayName: "Neha Gupta",
    emailLocalPart: "neha.gupta",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(27),
    heightCm: 168,
    city: "Kolkata",
    region: "West Bengal",
    religion: "Christian",
    education: "M.Sc",
    educationBand: "masters",
    profession: "Researcher",
    annualIncomeAmount: 700_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "eggetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "I work in a lab and spend evenings at the book fair or a quiet cafe. Faith matters to me, but kindness matters more. Hoping to meet someone curious about the world.",
    motherTongue: "Bengali",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Bengali", "English", "Hindi"],
    photoPath: "/profile5.avif",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 27,
      maxAge: 36,
      minHeightCm: 170,
      maxHeightCm: 190,
      countries: ["IN"],
      religions: ["Christian", "Hindu"],
      educationBands: ["masters", "doctorate"],
    },
  },
  {
    userId: "seed-rohit-kumar",
    displayName: "Rohit Kumar",
    emailLocalPart: "rohit.kumar",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(29),
    heightCm: 175,
    city: "Hyderabad",
    region: "Telangana",
    religion: "Hindu",
    education: "BBA",
    educationBand: "bachelors",
    profession: "Consultant",
    annualIncomeAmount: 480_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "non_vegetarian",
    smoking: "occasionally",
    drinking: "occasionally",
    aboutMe:
      "Consultant who actually likes client dinners. I play badminton twice a week and am trying to get better at Telugu. Looking for a partner who does not take life too seriously.",
    motherTongue: "Hindi",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "open",
    languagesSpoken: ["Hindi", "English"],
    photoPath: "/profile6.avif",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 24,
      maxAge: 31,
      minHeightCm: 152,
      maxHeightCm: 172,
      countries: ["IN"],
      religions: [],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-sanya-mehta",
    displayName: "Sanya Mehta",
    emailLocalPart: "sanya.mehta",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(24),
    heightCm: 160,
    city: "Pune",
    region: "Maharashtra",
    religion: "Jain",
    education: "BA",
    educationBand: "bachelors",
    profession: "Designer",
    annualIncomeAmount: 420_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "I design brand identities and paint on weekends. Raised Jain, I keep a vegetarian kitchen and love Pune's monsoon. Hoping for someone creative, grounded, and close to their family.",
    motherTongue: "Gujarati",
    familyType: "joint",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Gujarati", "Hindi", "English", "Marathi"],
    photoPath: "/profile7.avif",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 25,
      maxAge: 32,
      minHeightCm: 168,
      maxHeightCm: 188,
      countries: ["IN"],
      religions: ["Jain", "Hindu"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-arun-das",
    displayName: "Arun Das",
    emailLocalPart: "arun.das",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(31),
    heightCm: 178,
    city: "Jaipur",
    region: "Rajasthan",
    religion: "Buddhist",
    education: "B.E.",
    educationBand: "bachelors",
    profession: "Engineer",
    annualIncomeAmount: 600_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "Civil engineer who restores old havelis in my spare time. I meditate in the morning and cook simple Rajasthani food. Looking for a calm partner who enjoys slow travel.",
    motherTongue: "Hindi",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Hindi", "English"],
    photoPath: "/profile8.avif",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 25,
      maxAge: 33,
      minHeightCm: 152,
      maxHeightCm: 173,
      countries: ["IN"],
      religions: ["Buddhist", "Hindu"],
      educationBands: [],
    },
  },
  {
    userId: "seed-kavita-reddy",
    displayName: "Kavita Reddy",
    emailLocalPart: "kavita.reddy",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(26),
    heightCm: 170,
    city: "Ahmedabad",
    region: "Gujarat",
    religion: "Hindu",
    education: "MBBS",
    educationBand: "bachelors",
    profession: "Doctor",
    annualIncomeAmount: 620_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "eggetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "Resident doctor with long shifts and a soft spot for Gujarati snacks. I want a partner who understands odd hours and still wants to build a home together.",
    motherTongue: "Telugu",
    familyType: "nuclear",
    isManglik: "yes",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Telugu", "Gujarati", "English", "Hindi"],
    photoPath: "/profile9.avif",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 27,
      maxAge: 35,
      minHeightCm: 172,
      maxHeightCm: 190,
      countries: ["IN"],
      religions: ["Hindu"],
      educationBands: ["bachelors", "masters", "doctorate"],
    },
  },
  {
    userId: "seed-manoj-joshi",
    displayName: "Manoj Joshi",
    emailLocalPart: "manoj.joshi",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(32),
    heightCm: 180,
    city: "Lucknow",
    region: "Uttar Pradesh",
    religion: "Muslim",
    education: "M.Tech",
    educationBand: "masters",
    profession: "Architect",
    annualIncomeAmount: 750_000,
    incomeCurrency: "INR",
    maritalStatus: "divorced",
    diet: "non_vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "Architect, divorced two years ago, no children. I design homes and collect old Lucknow photographs. Looking for a second chapter with someone honest and warm.",
    motherTongue: "Hindi",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "open",
    languagesSpoken: ["Hindi", "English", "Urdu"],
    photoPath: "/profile10.avif",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 26,
      maxAge: 36,
      minHeightCm: 155,
      maxHeightCm: 175,
      countries: ["IN"],
      religions: ["Muslim", "Hindu"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-deepa-nair",
    displayName: "Deepa Nair",
    emailLocalPart: "deepa.nair",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(28),
    heightCm: 165,
    city: "Goa",
    region: "Goa",
    religion: "Christian",
    education: "PhD",
    educationBand: "doctorate",
    profession: "Researcher",
    annualIncomeAmount: 800_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "non_vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "Marine biologist based in Goa. I surf badly, cook well, and visit Kerala every Christmas. Looking for a partner who likes the sea and does not mind a sandy house.",
    motherTongue: "Malayalam",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "open",
    languagesSpoken: ["Malayalam", "English", "Hindi"],
    photoPath: "/profile11.avif",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 28,
      maxAge: 38,
      minHeightCm: 170,
      maxHeightCm: 190,
      countries: ["IN"],
      religions: ["Christian"],
      educationBands: ["masters", "doctorate"],
    },
  },
  {
    userId: "seed-priya-sharma",
    displayName: "Priya Sharma",
    emailLocalPart: "priya.sharma",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(26),
    heightCm: 163,
    city: "Mumbai",
    region: "Maharashtra",
    religion: "Hindu",
    education: "MBA",
    educationBand: "masters",
    profession: "Software Engineer",
    annualIncomeAmount: 600_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "Product engineer in Mumbai who still takes the local to work. I dance kathak twice a week and call my mother every evening. Hoping to meet someone grounded and funny.",
    motherTongue: "Hindi",
    familyType: "joint",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Hindi", "English", "Marathi"],
    photoPath: "/profile12.avif",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 26,
      maxAge: 34,
      minHeightCm: 170,
      maxHeightCm: 188,
      countries: ["IN"],
      religions: ["Hindu"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-ritu-bose",
    displayName: "Ritu Bose",
    emailLocalPart: "ritu.bose",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(27),
    heightCm: 163,
    city: "Surat",
    region: "Gujarat",
    religion: "Sikh",
    education: "BCA",
    educationBand: "bachelors",
    profession: "Marketing Manager",
    annualIncomeAmount: 530_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "non_vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "I run campaigns for textile brands and miss Kolkata street food. Weekends are for gurdwara and friends. Looking for a partner who is ambitious but kind at home.",
    motherTongue: "Bengali",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Bengali", "English", "Hindi", "Gujarati"],
    photoPath: "/profile13.avif",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 27,
      maxAge: 35,
      minHeightCm: 170,
      maxHeightCm: 188,
      countries: ["IN"],
      religions: ["Sikh", "Hindu"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-amar-chauhan",
    displayName: "Amar Chauhan",
    emailLocalPart: "amar.chauhan",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(30),
    heightCm: 175,
    city: "Indore",
    region: "Madhya Pradesh",
    religion: "Jain",
    education: "MA",
    educationBand: "masters",
    profession: "Teacher",
    annualIncomeAmount: 490_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "I teach literature at a college in Indore and write short stories. Simple food, morning walks, and a partner who likes books more than parties.",
    motherTongue: "Hindi",
    familyType: "joint",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Hindi", "English"],
    photoPath: "/profile14.avif",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 24,
      maxAge: 32,
      minHeightCm: 150,
      maxHeightCm: 170,
      countries: ["IN"],
      religions: ["Jain", "Hindu"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-sneha-roy",
    displayName: "Sneha Roy",
    emailLocalPart: "sneha.roy",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(26),
    heightCm: 168,
    city: "Nagpur",
    region: "Maharashtra",
    religion: "Christian",
    education: "LLB",
    educationBand: "bachelors",
    profession: "Lawyer",
    annualIncomeAmount: 710_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "non_vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "Litigation lawyer who still goes home for orange season. I want someone who respects my work hours and enjoys a good argument that ends with dinner.",
    motherTongue: "Bengali",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "open",
    languagesSpoken: ["Bengali", "English", "Hindi", "Marathi"],
    photoPath: "/profile15.avif",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 27,
      maxAge: 36,
      minHeightCm: 172,
      maxHeightCm: 190,
      countries: ["IN"],
      religions: ["Christian", "Hindu"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-aditya-jain",
    displayName: "Aditya Jain",
    emailLocalPart: "aditya.jain",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(28),
    heightCm: 173,
    city: "Bhubaneswar",
    region: "Odisha",
    religion: "Hindu",
    education: "B.Ed",
    educationBand: "bachelors",
    profession: "Teacher",
    annualIncomeAmount: 460_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "School teacher and temple volunteer. I cycle to work and spend holidays at Puri. Looking for a partner who likes a quiet life and a full house during festivals.",
    motherTongue: "Odia",
    familyType: "joint",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Odia", "Hindi", "English"],
    photoPath: "/profile16.avif",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 23,
      maxAge: 30,
      minHeightCm: 150,
      maxHeightCm: 168,
      countries: ["IN"],
      religions: ["Hindu", "Jain"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-pooja-desai",
    displayName: "Pooja Desai",
    emailLocalPart: "pooja.desai",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(25),
    heightCm: 160,
    city: "Patna",
    region: "Bihar",
    religion: "Muslim",
    education: "MPhil",
    educationBand: "masters",
    profession: "Consultant",
    annualIncomeAmount: 520_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "non_vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "Policy consultant who still prefers Patna over any metro. I read history and cook for anyone who visits. Looking for a partner who is patient and proud of where they come from.",
    motherTongue: "Hindi",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Hindi", "English", "Urdu"],
    photoPath: "/profile17.avif",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 26,
      maxAge: 34,
      minHeightCm: 168,
      maxHeightCm: 185,
      countries: ["IN"],
      religions: ["Muslim"],
      educationBands: ["masters", "doctorate"],
    },
  },
  {
    userId: "seed-sameer-khan",
    displayName: "Sameer Khan",
    emailLocalPart: "sameer.khan",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(31),
    heightCm: 183,
    city: "Chandigarh",
    region: "Chandigarh",
    religion: "Sikh",
    education: "B.Pharma",
    educationBand: "bachelors",
    profession: "Pharmacist",
    annualIncomeAmount: 630_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "non_vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "Pharmacist with a shop near the lake. I play hockey badly and host family langar when I can. Hoping to meet someone warm who wants to stay in the north.",
    motherTongue: "Punjabi",
    familyType: "joint",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Punjabi", "Hindi", "English"],
    photoPath: "/profile18.avif",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 25,
      maxAge: 33,
      minHeightCm: 155,
      maxHeightCm: 173,
      countries: ["IN"],
      religions: ["Sikh", "Hindu"],
      educationBands: ["bachelors", "masters"],
    },
  },
];
