import { dateOfBirthFromApproximateAge } from "@/domain/display/compute-age-from-date-of-birth";
import type { SeedMember } from "@/db/seed/seed-member-shape";

/** Eighteen India members. Each photo is unique across the whole catalog. */
export const indiaSeedProfiles: SeedMember[] = [
  {
    userId: "seed-karan-kapoor",
    displayName: "Karan Kapoor",
    emailLocalPart: "karan.kapoor",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(29),
    heightCm: 178,
    city: "Dehradun",
    region: "Uttarakhand",
    religion: "Hindu",
    education: "B.Tech",
    educationBand: "bachelors",
    profession: "Software Engineer",
    annualIncomeAmount: 1_400_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "I grew up in the hills and still hike Mussoorie every weekend. I write backend services for a product company and cook a proper Sunday dal. Looking for someone kind who wants a calm home and the occasional mountain trip.",
    motherTongue: "Hindi",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Hindi", "English"],
    photoPath: "/profile_male_1.avif",
    medicalStatus: "has_notes",
    medicalNotes: "Hypothyroidism, stable on a daily tablet. Annual check-ups are normal.",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 24,
      maxAge: 32,
      minHeightCm: 152,
      maxHeightCm: 175,
      countries: ["IN"],
      religions: ["Hindu"],
      educationBands: ["diploma", "bachelors", "masters"],
    },
  },
  {
    userId: "seed-rahul-verma",
    displayName: "Rahul Verma",
    emailLocalPart: "rahul.verma",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(28),
    heightCm: 170,
    city: "Delhi",
    region: "Delhi",
    religion: "Hindu",
    education: "B.Com",
    educationBand: "bachelors",
    profession: "Chartered Accountant",
    annualIncomeAmount: 920_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "Audit by day, cricket in Lodhi Garden on Sundays. Close to my parents in Delhi and hoping to stay in the city. I want a partner who values family dinners and honest conversations.",
    motherTongue: "Hindi",
    familyType: "joint",
    isManglik: "unknown",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Hindi", "English"],
    photoPath: "/profile_male_2.avif",
    medicalStatus: "clear",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 23,
      maxAge: 30,
      minHeightCm: 150,
      maxHeightCm: 170,
      countries: ["IN"],
      religions: ["Hindu", "Jain"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-ananya-singh",
    displayName: "Ananya Singh",
    emailLocalPart: "ananya.singh",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(25),
    heightCm: 162,
    city: "Bangalore",
    region: "Karnataka",
    religion: "Hindu",
    education: "MCA",
    educationBand: "masters",
    profession: "Data Analyst",
    annualIncomeAmount: 1_600_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "eggetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "I moved to Bangalore for work and stayed for the weather and the filter coffee. I like Cubbon Park walks, Hindi poetry, and weekend calls with my sister. Looking for someone thoughtful and ambitious.",
    motherTongue: "Hindi",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "open",
    languagesSpoken: ["Hindi", "English", "Kannada"],
    photoPath: "/profile_female_1.avif",
    medicalStatus: "clear",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 26,
      maxAge: 34,
      minHeightCm: 170,
      maxHeightCm: 190,
      countries: ["IN"],
      religions: ["Hindu"],
      educationBands: ["bachelors", "masters", "doctorate"],
    },
  },
  {
    userId: "seed-vikram-patel",
    displayName: "Vikram Patel",
    emailLocalPart: "vikram.patel",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(30),
    heightCm: 175,
    city: "Ahmedabad",
    region: "Gujarat",
    religion: "Hindu",
    education: "BBA",
    educationBand: "bachelors",
    profession: "Sales Manager",
    annualIncomeAmount: 1_250_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "I travel for work across western India and still make it home for Sunday dinner. I want a partner who is independent, laughs easily, and does not mind a Gujarati kitchen.",
    motherTongue: "Gujarati",
    familyType: "joint",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Gujarati", "Hindi", "English"],
    photoPath: "/profile_male_3.avif",
    medicalStatus: "has_notes",
    medicalNotes: "Thalassemia trait. No treatment needed; mentioned for family planning.",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 24,
      maxAge: 32,
      minHeightCm: 155,
      maxHeightCm: 175,
      countries: ["IN"],
      religions: ["Hindu", "Jain"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-neha-gupta",
    displayName: "Neha Gupta",
    emailLocalPart: "neha.gupta",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(27),
    heightCm: 166,
    city: "Kolkata",
    region: "West Bengal",
    religion: "Christian",
    education: "M.Sc",
    educationBand: "masters",
    profession: "Research Scientist",
    annualIncomeAmount: 1_100_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "eggetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "I work in a biotech lab and spend evenings at the book fair or a quiet cafe in Park Street. Faith matters to me, but kindness matters more. Hoping to meet someone curious about the world.",
    motherTongue: "Bengali",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Bengali", "English", "Hindi"],
    photoPath: "/profile_female_2.avif",
    hideIncome: true,
    medicalStatus: "clear",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 27,
      maxAge: 36,
      minHeightCm: 170,
      maxHeightCm: 190,
      countries: ["IN"],
      religions: ["Christian", "Hindu"],
      educationBands: ["masters", "doctorate"],
    },
  },
  {
    userId: "seed-rohit-kumar",
    displayName: "Rohit Kumar",
    emailLocalPart: "rohit.kumar",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(29),
    heightCm: 173,
    city: "Hyderabad",
    region: "Telangana",
    religion: "Hindu",
    education: "MBA",
    educationBand: "masters",
    profession: "Management Consultant",
    annualIncomeAmount: 1_850_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "non_vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "Consultant who actually likes client dinners. I play badminton twice a week and am trying to get better at Telugu. Looking for a partner who does not take life too seriously.",
    motherTongue: "Hindi",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "open",
    languagesSpoken: ["Hindi", "English"],
    photoPath: "/profile_male_4.avif",
    medicalStatus: "has_notes",
    medicalNotes: "Mild asthma, well controlled with an inhaler. No hospital visits in years.",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 24,
      maxAge: 31,
      minHeightCm: 152,
      maxHeightCm: 172,
      countries: ["IN"],
      religions: [],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-sanya-mehta",
    displayName: "Sanya Mehta",
    emailLocalPart: "sanya.mehta",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(24),
    heightCm: 157,
    city: "Pune",
    region: "Maharashtra",
    religion: "Jain",
    education: "B.Des",
    educationBand: "bachelors",
    profession: "Brand Designer",
    annualIncomeAmount: 780_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "I design brand identities and paint on weekends. Raised Jain, I keep a vegetarian kitchen and love Pune's monsoon. Hoping for someone creative, grounded, and close to their family.",
    motherTongue: "Gujarati",
    familyType: "joint",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Gujarati", "Hindi", "English", "Marathi"],
    photoPath: "/profile_female_3.avif",
    medicalStatus: "clear",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 25,
      maxAge: 32,
      minHeightCm: 168,
      maxHeightCm: 188,
      countries: ["IN"],
      religions: ["Jain", "Hindu"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-arun-das",
    displayName: "Arun Das",
    emailLocalPart: "arun.das",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(31),
    heightCm: 168,
    city: "Jaipur",
    region: "Rajasthan",
    religion: "Hindu",
    education: "B.E.",
    educationBand: "bachelors",
    profession: "Civil Engineer",
    annualIncomeAmount: 1_050_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "Civil engineer who restores old havelis in my spare time. I cook simple Rajasthani food and like slow travel. Looking for a calm partner who enjoys heritage walks more than clubs.",
    motherTongue: "Hindi",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Hindi", "English"],
    photoPath: "/profile_male_5.avif",
    medicalStatus: "has_notes",
    medicalNotes: "Recovered from ACL surgery in 2023. I walk and cycle without limits now.",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 25,
      maxAge: 33,
      minHeightCm: 152,
      maxHeightCm: 173,
      countries: ["IN"],
      religions: ["Hindu", "Jain"],
      educationBands: [],
    },
  },
  {
    userId: "seed-kavita-reddy",
    displayName: "Kavita Reddy",
    emailLocalPart: "kavita.reddy",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(26),
    heightCm: 164,
    city: "Hyderabad",
    region: "Telangana",
    religion: "Hindu",
    education: "MBBS",
    educationBand: "bachelors",
    profession: "Resident Doctor",
    annualIncomeAmount: 1_350_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "eggetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "Resident doctor with long shifts and a soft spot for Andhra meals. I want a partner who understands odd hours and still wants to build a home together.",
    motherTongue: "Telugu",
    familyType: "nuclear",
    isManglik: "yes",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Telugu", "English", "Hindi"],
    photoPath: "/profile_female_4.avif",
    medicalStatus: "clear",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 27,
      maxAge: 35,
      minHeightCm: 172,
      maxHeightCm: 190,
      countries: ["IN"],
      religions: ["Hindu"],
      educationBands: ["bachelors", "masters", "doctorate"],
    },
  },
  {
    userId: "seed-manoj-joshi",
    displayName: "Manoj Joshi",
    emailLocalPart: "manoj.joshi",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(32),
    heightCm: 181,
    city: "Lucknow",
    region: "Uttar Pradesh",
    religion: "Hindu",
    education: "M.Arch",
    educationBand: "masters",
    profession: "Architect",
    annualIncomeAmount: 1_300_000,
    incomeCurrency: "INR",
    maritalStatus: "divorced",
    diet: "vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "Architect, divorced two years ago, no children. I design homes and collect old Lucknow photographs. Looking for a second chapter with someone honest and warm.",
    motherTongue: "Hindi",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "open",
    languagesSpoken: ["Hindi", "English"],
    photoPath: "/profile_male_6.avif",
    medicalStatus: "clear",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 26,
      maxAge: 36,
      minHeightCm: 155,
      maxHeightCm: 175,
      countries: ["IN"],
      religions: ["Hindu"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-deepa-nair",
    displayName: "Deepa Nair",
    emailLocalPart: "deepa.nair",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(28),
    heightCm: 160,
    city: "Panaji",
    region: "Goa",
    religion: "Christian",
    education: "PhD",
    educationBand: "doctorate",
    profession: "Marine Biologist",
    annualIncomeAmount: 1_500_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "non_vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "Marine biologist based in Goa. I surf badly, cook well, and visit Kerala every Christmas. Looking for a partner who likes the sea and does not mind a sandy house.",
    motherTongue: "Malayalam",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "open",
    languagesSpoken: ["Malayalam", "English", "Hindi"],
    photoPath: "/profile_female_5.avif",
    medicalStatus: "has_notes",
    medicalNotes: "Seasonal asthma in the monsoon. Managed with a preventer inhaler.",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 28,
      maxAge: 38,
      minHeightCm: 170,
      maxHeightCm: 190,
      countries: ["IN"],
      religions: ["Christian"],
      educationBands: ["masters", "doctorate"],
    },
  },
  {
    userId: "seed-priya-sharma",
    displayName: "Priya Sharma",
    emailLocalPart: "priya.sharma",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(26),
    heightCm: 161,
    city: "Mumbai",
    region: "Maharashtra",
    religion: "Hindu",
    education: "MBA",
    educationBand: "masters",
    profession: "Product Engineer",
    annualIncomeAmount: 2_200_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "Product engineer in Mumbai who still takes the local to work. I dance kathak twice a week and call my mother every evening. Hoping to meet someone grounded and funny.",
    motherTongue: "Hindi",
    familyType: "joint",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Hindi", "English", "Marathi"],
    photoPath: "/profile_female_6.avif",
    medicalStatus: "clear",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 26,
      maxAge: 34,
      minHeightCm: 170,
      maxHeightCm: 188,
      countries: ["IN"],
      religions: ["Hindu"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-ritu-bose",
    displayName: "Ritu Bose",
    emailLocalPart: "ritu.bose",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(27),
    heightCm: 163,
    city: "Kolkata",
    region: "West Bengal",
    religion: "Hindu",
    education: "BBA",
    educationBand: "bachelors",
    profession: "Marketing Manager",
    annualIncomeAmount: 980_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "non_vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "I run campaigns for a consumer brand and miss street food the week I travel. Weekends are for family and friends in South Kolkata. Looking for a partner who is ambitious but kind at home.",
    motherTongue: "Bengali",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Bengali", "English", "Hindi"],
    photoPath: "/profile_female_7.avif",
    medicalStatus: "clear",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 27,
      maxAge: 35,
      minHeightCm: 170,
      maxHeightCm: 188,
      countries: ["IN"],
      religions: ["Hindu"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-amar-chauhan",
    displayName: "Amar Chauhan",
    emailLocalPart: "amar.chauhan",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(30),
    heightCm: 172,
    city: "Amritsar",
    region: "Punjab",
    religion: "Sikh",
    education: "MA",
    educationBand: "masters",
    profession: "College Lecturer",
    annualIncomeAmount: 680_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "I teach literature and write short stories. Simple food, morning walks to the Harmandir Sahib, and a partner who likes books more than parties.",
    motherTongue: "Punjabi",
    familyType: "joint",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Punjabi", "Hindi", "English"],
    photoPath: "/profile_male_7.avif",
    medicalStatus: "clear",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 24,
      maxAge: 32,
      minHeightCm: 150,
      maxHeightCm: 170,
      countries: ["IN"],
      religions: ["Sikh", "Hindu"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-sneha-roy",
    displayName: "Sneha Roy",
    emailLocalPart: "sneha.roy",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(26),
    heightCm: 167,
    city: "Nagpur",
    region: "Maharashtra",
    religion: "Christian",
    education: "LLB",
    educationBand: "bachelors",
    profession: "Litigation Lawyer",
    annualIncomeAmount: 1_150_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "non_vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "Litigation lawyer who still goes home for orange season. I want someone who respects my work hours and enjoys a good argument that ends with dinner.",
    motherTongue: "Bengali",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "open",
    languagesSpoken: ["Bengali", "English", "Hindi", "Marathi"],
    photoPath: "/profile_female_8.avif",
    medicalStatus: "clear",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 27,
      maxAge: 36,
      minHeightCm: 172,
      maxHeightCm: 190,
      countries: ["IN"],
      religions: ["Christian", "Hindu"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-aditya-jain",
    displayName: "Aditya Jain",
    emailLocalPart: "aditya.jain",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(28),
    heightCm: 169,
    city: "Bhubaneswar",
    region: "Odisha",
    religion: "Jain",
    education: "B.Ed",
    educationBand: "bachelors",
    profession: "School Teacher",
    annualIncomeAmount: 580_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "School teacher and temple volunteer. I cycle to work and spend holidays at Puri. Looking for a partner who likes a quiet life and a full house during festivals.",
    motherTongue: "Odia",
    familyType: "joint",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Odia", "Hindi", "English"],
    photoPath: "/profile_male_8.avif",
    medicalStatus: "clear",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 23,
      maxAge: 30,
      minHeightCm: 150,
      maxHeightCm: 168,
      countries: ["IN"],
      religions: ["Jain", "Hindu"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-pooja-desai",
    displayName: "Pooja Desai",
    emailLocalPart: "pooja.desai",
    country: "IN",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(25),
    heightCm: 158,
    city: "Vadodara",
    region: "Gujarat",
    religion: "Hindu",
    education: "M.A. Public Policy",
    educationBand: "masters",
    profession: "Policy Consultant",
    annualIncomeAmount: 1_050_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "Policy consultant who still prefers Vadodara over any metro. I read history and cook for anyone who visits. Looking for a partner who is patient and proud of where they come from.",
    motherTongue: "Gujarati",
    familyType: "nuclear",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Gujarati", "Hindi", "English"],
    photoPath: "/profile_female_9.avif",
    medicalStatus: "has_notes",
    medicalNotes: "Thalassemia trait. Healthy otherwise; shared for future family planning.",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 26,
      maxAge: 34,
      minHeightCm: 168,
      maxHeightCm: 185,
      countries: ["IN"],
      religions: ["Hindu", "Jain"],
      educationBands: ["masters", "doctorate"],
    },
  },
  {
    userId: "seed-sameer-khan",
    displayName: "Sameer Khan",
    emailLocalPart: "sameer.khan",
    country: "IN",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(31),
    heightCm: 176,
    city: "Chandigarh",
    region: "Chandigarh",
    religion: "Muslim",
    education: "B.Pharm",
    educationBand: "bachelors",
    profession: "Pharmacist",
    annualIncomeAmount: 850_000,
    incomeCurrency: "INR",
    maritalStatus: "never_married",
    diet: "non_vegetarian",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "I run a pharmacy near the lake and host family dinners on Fridays. Hoping to meet someone warm who wants to stay in the north and build a steady life.",
    motherTongue: "Urdu",
    familyType: "joint",
    isManglik: "no",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["Urdu", "Hindi", "English", "Punjabi"],
    photoPath: "/profile_male_9.avif",
    medicalStatus: "clear",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 25,
      maxAge: 33,
      minHeightCm: 155,
      maxHeightCm: 173,
      countries: ["IN"],
      religions: ["Muslim"],
      educationBands: ["bachelors", "masters"],
    },
  },
];
