import { dateOfBirthFromApproximateAge } from "@/domain/display/compute-age-from-date-of-birth";
import type { SeedMember } from "@/db/seed/seed-member-shape";

/** Four US members. Photos reuse the existing public/profile*.avif set. */
export const unitedStatesSeedProfiles: SeedMember[] = [
  {
    userId: "seed-daniel-okonkwo",
    displayName: "Daniel Okonkwo",
    emailLocalPart: "daniel.okonkwo",
    country: "US",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(31),
    heightCm: 183,
    city: "New York",
    region: "New York",
    religion: "Christian",
    education: "MBA",
    educationBand: "masters",
    profession: "Finance analyst",
    annualIncomeAmount: 145_000,
    incomeCurrency: "USD",
    maritalStatus: "never_married",
    diet: "no_preference",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "I work in midtown and still cook Nigerian food on Sundays. I want a marriage, not a situationship — someone who likes cities, family, and a shared calendar.",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["English"],
    ethnicity: "black",
    photoPath: "/profile2.avif",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 26,
      maxAge: 35,
      minHeightCm: 155,
      maxHeightCm: 175,
      countries: ["US"],
      religions: ["Christian"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-maya-patel",
    displayName: "Maya Patel",
    emailLocalPart: "maya.patel",
    country: "US",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(28),
    heightCm: 165,
    city: "Austin",
    region: "Texas",
    religion: "Hindu",
    education: "Bachelor's in Design",
    educationBand: "bachelors",
    profession: "UX designer",
    annualIncomeAmount: 98_000,
    incomeCurrency: "USD",
    maritalStatus: "never_married",
    diet: "vegetarian",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "First-generation American, vegetarian kitchen, live music on weekends. I want a partner who is serious about marriage and easy to travel with.",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["English", "Gujarati"],
    ethnicity: "asian",
    photoPath: "/profile5.avif",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 28,
      maxAge: 36,
      minHeightCm: 170,
      maxHeightCm: 190,
      countries: ["US"],
      religions: ["Hindu", "None", "prefer_not_to_say"],
      educationBands: ["bachelors", "masters"],
    },
  },
  {
    userId: "seed-james-miller",
    displayName: "James Miller",
    emailLocalPart: "james.miller",
    country: "US",
    gender: "male",
    seekingGender: "female",
    dateOfBirth: dateOfBirthFromApproximateAge(34),
    heightCm: 180,
    city: "Chicago",
    region: "Illinois",
    religion: "prefer_not_to_say",
    education: "J.D.",
    educationBand: "doctorate",
    profession: "Attorney",
    annualIncomeAmount: 160_000,
    incomeCurrency: "USD",
    maritalStatus: "divorced",
    diet: "no_preference",
    smoking: "never",
    drinking: "occasionally",
    aboutMe:
      "Divorced, no kids, work in civil rights law. I run along the lake and host Friendsgiving. Looking for a second marriage with someone emotionally available.",
    hasChildren: "none",
    wantsChildren: "open",
    languagesSpoken: ["English"],
    ethnicity: "white",
    photoPath: "/profile8.avif",
    seedWillReciprocateLikes: false,
    preference: {
      minAge: 28,
      maxAge: 40,
      minHeightCm: 155,
      maxHeightCm: 178,
      countries: ["US"],
      religions: [],
      educationBands: ["bachelors", "masters", "doctorate"],
    },
  },
  {
    userId: "seed-sofia-nguyen",
    displayName: "Sofia Nguyen",
    emailLocalPart: "sofia.nguyen",
    country: "US",
    gender: "female",
    seekingGender: "male",
    dateOfBirth: dateOfBirthFromApproximateAge(29),
    heightCm: 160,
    city: "Seattle",
    region: "Washington",
    religion: "Buddhist",
    education: "Master's in Public Health",
    educationBand: "masters",
    profession: "Epidemiologist",
    annualIncomeAmount: 112_000,
    incomeCurrency: "USD",
    maritalStatus: "never_married",
    diet: "no_preference",
    smoking: "never",
    drinking: "never",
    aboutMe:
      "Public health nerd, weekend hiker, close to my Vietnamese family. I want children and a partner who will show up for both holidays and hard weeks.",
    hasChildren: "none",
    wantsChildren: "yes",
    languagesSpoken: ["English", "Vietnamese"],
    ethnicity: "asian",
    photoPath: "/profile7.avif",
    seedWillReciprocateLikes: true,
    preference: {
      minAge: 29,
      maxAge: 38,
      minHeightCm: 170,
      maxHeightCm: 188,
      countries: ["US"],
      religions: ["Buddhist", "Christian", "None", "prefer_not_to_say"],
      educationBands: ["bachelors", "masters", "doctorate"],
    },
  },
];
