import type { CountryCatalog } from "@/domain/countries/supported-countries";

export const indiaCatalog: CountryCatalog = {
  code: "IN",
  englishName: "India",
  currency: "INR",
  currencySymbol: "₹",
  heightDisplayUnit: "feet_and_inches",
  incomeSliderMax: 10_000_000,
  incomeSliderStep: 50_000,
  religions: [
    { value: "Hindu", label: "Hindu" },
    { value: "Muslim", label: "Muslim" },
    { value: "Christian", label: "Christian" },
    { value: "Sikh", label: "Sikh" },
    { value: "Jain", label: "Jain" },
    { value: "Buddhist", label: "Buddhist" },
    { value: "Zoroastrian", label: "Zoroastrian" },
    { value: "Judaism", label: "Judaism" },
    { value: "Donyi-Polo", label: "Donyi-Polo" },
    { value: "Sarna", label: "Sarna" },
    { value: "Gondi", label: "Gondi" },
    { value: "Baháʼí Faith", label: "Baháʼí Faith" },
    { value: "Atheism", label: "Atheism" },
    { value: "Other", label: "Other" },
  ],
  cities: [
    { city: "Mumbai", region: "Maharashtra" },
    { city: "Delhi", region: "Delhi" },
    { city: "Bangalore", region: "Karnataka" },
    { city: "Hyderabad", region: "Telangana" },
    { city: "Chennai", region: "Tamil Nadu" },
    { city: "Kolkata", region: "West Bengal" },
    { city: "Pune", region: "Maharashtra" },
    { city: "Ahmedabad", region: "Gujarat" },
    { city: "Jaipur", region: "Rajasthan" },
    { city: "Lucknow", region: "Uttar Pradesh" },
    { city: "Surat", region: "Gujarat" },
    { city: "Indore", region: "Madhya Pradesh" },
    { city: "Nagpur", region: "Maharashtra" },
    { city: "Chandigarh", region: "Chandigarh" },
    { city: "Dehradun", region: "Uttarakhand" },
    { city: "Goa", region: "Goa" },
    { city: "Bhubaneswar", region: "Odisha" },
    { city: "Patna", region: "Bihar" },
  ],
  extraFields: {
    motherTongue: true,
    community: true,
    familyType: true,
    onlyChild: false,
    ethnicity: false,
    manglik: true,
    requirePrivacyConsent: false,
  },
};

export const indiaMotherTongueOptions = [
  "Hindi",
  "English",
  "Bengali",
  "Telugu",
  "Marathi",
  "Tamil",
  "Gujarati",
  "Urdu",
  "Kannada",
  "Odia",
  "Malayalam",
  "Punjabi",
  "Assamese",
  "Other",
] as const;
